### ISSUE TITLE
ASAN下报内存泄漏

### ISSUE THREAD

**Issue by gajin2** [starwing/lua-protobuf#270]
OS：RockyLinux 9.4
Lua: RHEL9自带的luajit包：luajit-devel

ASAN输出：
```text
Indirect leak of 23 byte(s) in 1 object(s) allocated from:
    #0 0x7fb8ae0b4a07 in __interceptor_malloc (/usr/lib64/libasan.so.6+0xb4a07)
    #1 0xc5fe83 in pbN_newname common/utils/pb.h:1022
    #2 0xc6017b in pb_newname common/utils/pb.h:1079
    #3 0xc62c01 in pbL_loadFile common/utils/pb.h:1671
    #4 0xc6302a in pb_load common/utils/pb.h:1695
    #5 0xc6775e in Lpb_loadfile common/utils/pb.c:1233
    #6 0x7fb8adf78a9a  (/lib64/libluajit-5.1.so.2+0xaa9a)
```

自己修改静态编译到程序里，只修改了`luaopen_pb`  :
```c
    //luaL_newlib(L, libs);
    luaL_register(L, "pb", libs);
```

**Comment by starwing** [comment]
Thanks for reporting. I will look into this.
